### ISSUE TITLE
there is one toast with message malformed JSON

### ISSUE THREAD

**Issue by ghabiamin** [dan-zx/rox-android#1]

**Comment by dan-zx** [comment]
What is the message? Do you have any screenshot? Where did you find it?

**Comment by ghabiamin** [comment]
![Uploading json.png…]()

**Comment by ghabiamin** [comment]
i will publish a screenshot about the problem

**Comment by ghabiamin** [comment]
![json](https://cloud.githubusercontent.com/assets/8716872/8246746/e2a0463c-1643-11e5-9688-48d87c1b49ba.png)

**Comment by dan-zx** [comment]
This error is because I change the server location, sorry.

I suggest you not to use this app right now because the app is not intended to be in production; moreover the app is only available in some cities of Mexico.

**Comment by aminghabi** [comment]
So can u tell me how i can make this app working in my city ? thanks :)

**Comment by dan-zx** [comment]
@aminghabi It's a bit complicated, in general: build a Neo4j database for your city, create an app in Foursquare, publish RoX web services somewhere, change tokens, and… money :cry:

I really want this app in Google Play but I don't have the resources to support the whole world, not even my own country :disappointed:
